### ISSUE TITLE
FC mapping name should be optional parameter as in REST API

### ISSUE THREAD

**Issue by sumitguptaibm** [ansible-collections/ibm.storage_virtualize#12]
##### SUMMARY

FC Mapping name is an optional parameter in REST API and CLI but it is put as mandatory in ansible module
CLI can be run as (without mentioning FC mapping name): svctask mkfcmap -cleanrate 0 -copyrate 0 -source volume1 -target volume1_02
##### ISSUE TYPE
- Bug Report
ibm_svc_manage_flashcopy module needs to be changed for make FC mapping name field as optional. 
##### COMPONENT NAME

module: ibm_svc_manage_flashcopy
plugin: Ansible plugin for Storage Virtualize
task: Map a volume to another for flashcopy (Create a mapping)
##### ANSIBLE VERSION

```paste below
  ansible [core 2.12.0]
  executable location = /usr/bin/ansible
  python version = 3.9.17 (main, Jun  6 2023, 20:11:21) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION

```paste below
Collection             Version
---------------------- -------
ibm.storage_virtualize 2.0.0  
```

##### CONFIGURATION

```paste below
sumit@ubuntuhost:~$ ansible-config dump --only-changed
sumit@ubuntuhost:~$ 

```

##### OS / ENVIRONMENT

Host: Ubuntu
Target: SVC 8.6.0

##### STEPS TO REPRODUCE

```yaml

name: Create a FlashCopy
  hosts: localhost
  vars:
    - clustername: "{{ip}}"
    - username: superuser
    - password: Pa22w0rd!
    - domain: domain
    - volume_names: "{{volume_name}}"
    - snapshot_pool: "{{snapshot_pool}}"
  collections:
    - ibm.storage_virtualize
  gather_facts: no
  connection: local
  tasks:
    - name: Create a FlashCopy to a Volume
      ibm_sv_manage_snapshot:
        clustername: "{{clustername}}"
        username: "{{username}}"
        password: "{{password}}"
        src_volume_names: "{{volume_names}}"
        snapshot_pool: "{{snapshot_pool}}"
        state: present

```

##### EXPECTED RESULTS

When we don't give FC mapping "name" attribute, mapping should be created by Ansible.

##### ACTUAL RESULTS

ansible-playbook failed showing that 'name' is a mandatory parameter and it is missing.

```paste below

```
