### ISSUE TITLE
Add detail information to Drives via lsdrive detail api call

### ISSUE THREAD

**Issue by cueball23** [ansible-collections/ibm.storage_virtualize#19]
##### SUMMARY
Add detail information to Drives vial lsdrive detail api call.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ibm_svc_info.py

##### ADDITIONAL INFORMATION
Currently there is no way to get the Firmware Information for each drive.

Overview information for drives contains
```yaml
    - auto_manage: 
      capacity: 
      drive_class_id:
      enclosure_id: 
      error_sequence_number: ''
      id: 
      mdisk_id: 
      mdisk_name:
      member_id: 
      node_id: 
      node_name: 
      slot_id: 
      status: 
      tech_type:
      use: 
```

detail call includes

```yaml
    - FPGA_level: ''
      FRU_identity: 
      FRU_part_number: 
      RPM: ''
      UID: 
      auto_manage: 
      block_size: ''
      capacity: 
      compressed: ''
      date_of_manufacture: ''
      drive_class_id: ''
      effective_used_capacity: ''
      enclosure_id: ''
      error_sequence_number: ''
      firmware_level: 
      id: ''
      interface_speed: 
      mdisk_id: ''
      mdisk_name: 
      member_id: ''
      node_id: ''
      node_name: ''
      physical_capacity: 
      physical_used_capacity: ''
      port_1_status: 
      port_2_status: 
      product_id: ''
      protection_enabled: ''
      quorum_id: ''
      replacement_date: ''
      slot_id: ''
      status: 
      tech_type: 
      transport_protocol: 
      use: member
      vendor_id: 
      write_endurance_usage_rate: ''
      write_endurance_used: ''
```
