### ISSUE TITLE
Ansible svcinfo with lsvolumesnapshot fails with: filtervalue is not supported in command.

### ISSUE THREAD

**Issue by ryoung1us** [ansible-collections/ibm.storage_virtualize#51]
##### SUMMARY
ibm.storage_virtualize.ibm_svcinfo_command   with  svcinfo lsvolumesnapshot and a filtervalue fails with:
filtervalue is not supported in command

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm.storage_virtualize.ibm_svcinfo_command

##### ANSIBLE VERSION

``ansible [core 2.14.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansibleservice/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansibleservice/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```ibm.storage_virtualize  2.5.0
```

##### CONFIGURATION

```ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles']
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansibleservice
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 100
```

##### OS / ENVIRONMENT

 5.14.0-362.24.1.el9_3.s390x #1 SMP Thu Feb 15 07:18:07 EST 2024 s390x s390x s390x GNU/Linux

##### STEPS TO REPRODUCE

```
  - name: Run svcinfo lvvolumesnapshot
      ibm.storage_virtualize.ibm_svcinfo_command:
        command:  "svcinfo lsvolumesnapshot -filtervalue snapshot_name:ansible_bootvol_test2rgy "
        clustername: "cluster1"
        username: "{{fs95_admin}}"
        password: "{{admin_pass}}"
        log_path: /tmp/ansible.log

```

##### EXPECTED RESULTS
We expect to be able to list volume snapshots with the same filter capability as the CLI.

##### ACTUAL RESULTS
fatal: [localhost]: FAILED! => {"changed": false, "msg": "'filtervalue' is not supported in command."}
